{"level":"error","message":"login failed login failed","stack":"Error: login failed\n    at login (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\src\\routes\\auth\\controller.js:33:11)\n    at newFn (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at validate (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\src\\routes\\controller.js:28:5)\n    at newFn (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at middleware (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\node_modules\\express-validator\\src\\middlewares\\check.js:16:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
{"level":"error"}
{"level":"error","message":"something failed outside"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:28:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"Pr is not defined Pr is not defined","stack":"ReferenceError: Pr is not defined\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:28:10)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:30:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:30:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"","stack":"Error\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:28:25)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:30:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:28:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:31:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:28:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:28:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:28:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:29:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:33:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:33:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:33:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:33:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:33:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:36:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:33:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:33:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:36:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:33:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:38:7)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"something failde outside promise something failde outside promise","stack":"Error: something failde outside promise\n    at Object.<anonymous> (E:\\Sepideh\\Projects\\Node.js Course\\Auth-Project\\index.js:35:26)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)\n    at Module.load (node:internal/modules/cjs/loader:1037:32)\n    at Module._load (node:internal/modules/cjs/loader:878:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47"}
